# Generated by Django 4.2.6 on 2023-10-19 08:02
import random
from django.db import migrations


def add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    all_products = Product.objects.all()

    # we choose a random number from 100 000 000 to 999 999 999 both inclusive and fill each product barcode with it
    all_barcodes = random.sample(
        range(100000000, 1000000000),
        len(all_products)
    )
    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


def reverse_add_barcode(apps, schema_editor):
    Product = apps.get_model("main_app", "Product")
    for product in Product.objects.all():
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):

    dependencies = [('main_app', '0004_product_barcode')]

    operations = [
        migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
