# Generated by Django 3.2.7 on 2023-11-11 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0, 'The rating must be between 0.0 and 10.0'), django.core.validators.MaxValueValidator(10.0, 'The rating must be between 0.0 and 10.0')]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='release_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990, 'The release year must be between 1990 and 2023'), django.core.validators.MaxValueValidator(2023, 'The release year must be between 1990 and 2023')]),
        ),
    ]
