# Generated by Django 3.2.7 on 2023-10-21 10:38

from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# main_app.migrations.0002_migrate_unique_brands

def create_unique_brands(apps, schema_editor):

    shoe = apps.get_model("main_app", "Shoe")
    unique_shoes = apps.get_model("main_app", "UniqueBrands")

    db_alias = schema_editor.connection.alias

    unique_shoes_names = shoe.objects.values_list("brand", flat=True).distinct()

    for s_n in unique_shoes_names:
        unique_shoes.objects.using(db_alias).create(brand_name=s_n)

def reverse_create_unique_brands(apps, schema_editor):
    print("Success")

class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_migrate_unique_brands')]

    initial = True

    dependencies = [
        ('main_app', '0002_migrate_unique_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RunPython(
            code=create_unique_brands,
            reverse_code=reverse_create_unique_brands,
        ),
    ]
