# Generated by Django 4.2.6 on 2023-10-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
    ]
