# Generated by Django 3.2.7 on 2023-10-22 07:40

from django.db import migrations


# In order to set age group, we need to fill al data in the table and then restart the whole migration 0009
def set_age_group(apps, schema_editor):

    Person = apps.get_model("main_app", "Person")
    all_persons = Person.objects.all()

    for person in all_persons:
        if person.age <= 12:
            person.age_group = "Child"
        elif person.age <= 17:
            person.age_group = "Teen"
        else:
            person.age_group = "Adult"
        person.save()

def reverse_set_age_group(apps, schema_editor):
    Person = apps.get_model("main_app", "Person")
    all_persons = Person.objects.all()
    for person in all_persons:
        person.group = "No age group"
        person.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=reverse_set_age_group)
    ]
