# Generated by Django 3.2.7 on 2023-10-23 20:39

from django.db import migrations


def set_price_category(apps, schema_editor):

    Item = apps.get_model("main_app", "Item")
    all_items = Item.objects.all()

    for item in all_items:
        if item.price <= 10:
            item.rarity = "Rare"
        elif item.price <= 20:
            item.rarity = "Very Rare"
        elif item.price <= 30:
            item.rarity = "Extremely Rare"
        else:
            item.rarity = "Mega Rare"

    Item.objects.bulk_update(all_items, ["rarity"])

def unset_price_category(apps, schema_editor):
    Item = apps.get_model("main_app", "Item")
    all_items = Item.objects.all()

    for item in all_items:
        item.rarity = "empty"

    Item.objects.bulk_update(all_items, ["rarity"])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.RunPython(set_price_category, reverse_code=unset_price_category)
    ]
