# Generated by Django 3.2.7 on 2023-10-23 20:54

from django.db import migrations

def set_price_smartphones(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_smartphones = Smartphone.objects.all()

    for phone in all_smartphones:
        phone.price = len(phone.brand) * 120
        phone.save()

def reset_price_smartphones(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_smartphones = Smartphone.objects.all()

    for phone in all_smartphones:
        phone.price = 0
        phone.save()

def set_category_smartphones(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_smartphones = Smartphone.objects.all()

    for phone in all_smartphones:
        if phone.price < 750:
            phone.category = "Cheap"
        else:
            phone.category = "Expensive"
        phone.save()


def reset_category_smartphones(apps, schema_editor):
    Smartphone = apps.get_model("main_app", "Smartphone")
    all_smartphones = Smartphone.objects.all()

    for phone in all_smartphones:
        phone.category = "empty"
        phone.save()

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_smartphones, reverse_code=reset_price_smartphones),
        migrations.RunPython(set_category_smartphones, reverse_code=reset_category_smartphones)
    ]
