# Generated by Django 3.2.7 on 2023-10-23 21:13

from django.db import migrations
from django.utils import timezone


def update_data_according_status(apps, schema_editor):
    Order = apps.get_model("main_app", "Order")

    for order in Order.objects.all():
        if order.status == "Pending":
            order.delivery = order.delivery + timezone.timedelta(days=3)
            order.save()

        elif order.status == "Completed":
            order.warranty = "24 months"
            order.save()

        elif order.status == "Cancelled":
            order.delete()



def rollback_data_according_status(apps, schema_editor):
    Order = apps.get_model("main_app", "Order")

    for order in Order.objects.all():
        if order.status == "Pending":
            order.delivery = None

        elif order.status == "Completed":
            order.warranty = "No warranty"

        order.save()

    Order.objects.bulk_update(Order.objects.all(), ["delivery", "warranty"])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
        migrations.RunPython(update_data_according_status, reverse_code=rollback_data_according_status)
    ]
