# Generated by Django 3.2.7 on 2023-10-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
    ]
