# Generated by Django 3.2.7 on 2023-10-23 21:13

from django.db import migrations
from datetime import timedelta


def update_data_according_status(apps, schema_editor):
    Order = apps.get_model("main_app", "Order")
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == "Pending":
            order.delivery = order.delivery + timedelta(days=3)

        elif order.status == "Completed":
            order.warranty = "24 months"

        elif order.status == "Cancelled":
            order.delete()

    Order.objects.bulk_update(all_orders, ["delivery", "warranty"])


def rollback_data_according_status(apps, schema_editor):
    Order = apps.get_model("main_app", "Order")
    all_orders = Order.objects.all()

    for order in all_orders:
        order.delivery = order.delivery - timedelta(days=3)
        order.warranty = "No warranty"

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
        migrations.RunPython(update_data_according_status, reverse_code=rollback_data_according_status)
    ]
